[package]
authors = ["Yuuki Toriyama <github@toriyama.dev>"]
edition = "2021"
name = "torilang"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "compiler"
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/main.rs"

[dependencies]
